version: '3'

services:

  app:
    build:
      context: ./
    container_name: app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network
    

  mongodb:
    image: mongo
    restart: always
    tty: true
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network


networks:
  app-network:
    driver: bridge